generator:
  class: aTagAdminGenerator
  param:
    model_class:           Tag
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          a_tag_admin
    with_doctrine_route:   1
    
    
    config:
      
      list:
        title: Tags Admin
        display: [ =name, tag_aMediaItem, tag_aPage ]
        fields:
          name:
            label: Tag
          tag_aPage:
            label: Pages
          tag_aMediaItem:
            label: Media
          tag_aEvent:
            label: Events
        object_actions: []
        actions:
          new:
            label: New Tag
            action: new
            params:
              class: a-btn big icon a-add alt
      
      form:
        # When you use these you break the addition of new categorizable types in new plugins,
        # including the blog plugin. See PluginaCategoryForm for the right approach to limiting
        # this with useFields while still including the checkboxes for new types of categorizable stuff
        
        # fields:   [ name, groups_list, users_list ]
        # display:  [ name, groups_list, users_list ]

      
      filter:
        # When you use these you break the addition of new categorizable types in new plugins,
        # including the blog plugin. See PluginaCategoryFormFilter for the right approach to limiting
        # this with useFields while still including the filters for new types of categorizable stuff
        
        # fields:  [  groups_list, users_list ]
        # display: [  groups_list, users_list ]
        
      edit:
        title: Edit Tag
        
      new:
        title: New Tag
        